### ISSUE TITLE
nil value WeaponInformation

### ISSUE THREAD

**Issue by OfficialRDB** [qbcore-framework/qb-anticheat#16]
This error came up in the console after I did all the updates from the past days

**client/main.lua:193**
`attempt to index a nil value (local 'WeaponInformation'`

**Comment by xenfovn** [comment]
some problem 
![image](https://user-images.githubusercontent.com/55439243/141699685-fa75145a-836a-4acf-8b9d-1afd2c3f25bd.png)

**Comment by Krizmatic** [comment]
Same here
