### ISSUE TITLE
Error in client console

### ISSUE THREAD

**Issue by DevDokus** [qbcore-framework/qb-anticheat#26]
Wanted to let you guys know this error i receive when loading into the server
![image](https://user-images.githubusercontent.com/49053928/150039059-5df66608-8b47-4a9e-a3ca-6459dd3fd077.png)

**Comment by SemperCertusetFidelis** [comment]
'onResourceStop' does not have a source. So source is nil.

https://docs.fivem.net/docs/scripting-reference/events/list/onResourceStop/

**Comment by HellraiserTwo** [comment]
The problem is that `DropPlayer` native is a server-side native, It cannot be used client-side.
