### ISSUE TITLE
Anticheat detects fine but never bans

### ISSUE THREAD

**Issue by meistroburger** [qbcore-framework/qb-anticheat#27]
The anticheat works fine, it detects hackers/modders but actualy I've to manualy ban them, takes a lot of time and should be automated If possible. I have build my own solution, in the meantime but it should be working instead of "Player banned! of course not this is a test, duhhhh"

**Comment by SemperCertusetFidelis** [comment]
I'm looking into this as well. I think the issue is:

`local player = PlayerId()`   ->   "This returns YOUR 'identity' as a Player type.  Always returns 0 in story mode. "

So that's the wrong ID?

**Comment by SemperCertusetFidelis** [comment]
This fixed it for me https://github.com/qbcore-framework/qb-anticheat/pull/23
